//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDBContextEntities : DbContext
    {
        public HospitalDBContextEntities()
            : base("name=HospitalDBContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Appointments> Appointments1 { get; set; }
        public virtual DbSet<Doctors> Doctors1 { get; set; }
        public virtual DbSet<MedicalUnits> MedicalUnits1 { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
    }
}
